type Fields = [
  { key: 'key'; name: 'номер' },
  { key: 'date'; name: 'дата' },
  { key: 'uuid'; name: 'id'; bx: 'UF_CRM_1699614246981' },
  { key: 'proveden'; name: 'Проведен' },
  { key: 'delete'; name: 'ПометкаУдаления' },
  { key: 'cost'; name: 'ПлановаяСтоимость' },
  { key: 'type '; name: 'ВидОперации' },
  { key: 'next_date'; name: 'ДатаСледующейПоверки' },
  { key: 'exec'; name: 'Исполнитель' },
  { key: 'count'; name: 'КоличествоСчетчиков' },
  { key: 'contact '; name: 'КонтактноеЛицо' },
  { key: 'total'; name: 'СуммаДокумента' },
  { key: 'desc'; name: 'ОписаниеЗаявки' },
  { key: 'manager'; name: 'Ответственный' },
  { key: 'ID_1C'; name: 'ID_1C' },
  { key: 'date'; name: 'ПланируемаяДата' },
  { key: 'time'; name: 'ПланируемоеВремя' },
  { key: 'district'; name: 'РайонГорода' },
  { key: 'ticket_status'; name: 'СтатусЗаявки' },
  { key: 'uk'; name: 'УправляющаяКомпания' },
  { key: 'time_range'; name: 'ЖелаемыйИнтервал' },
  { key: 'invoice'; name: 'БезналичныйРасчет' },
  { key: 'phone'; name: 'Телефон' },
  { key: 'requester'; name: 'Заказчик' },
  { key: 'fullname'; name: 'НаименованиеПолное' },
  { key: 'contact'; name: 'ОсновноеКонтактноеЛицо' },
  { key: 'customer'; name: 'Абонент' },
  { key: 'customer_type'; name: 'ТипАбонента' },
  { key: 'customer_lastname'; name: 'Фамилия' },
  { key: 'customer_fisrtname'; name: 'Имя' },
  { key: 'customer_middlename'; name: 'Отчество' },
  { key: 'address_region'; name: 'Регион' },
  { key: 'address_area'; name: 'Округ' },
  { key: 'address_district'; name: 'абРайон' },
  { key: 'address_city'; name: 'НасПункт' },
  { key: 'address_street'; name: 'Улица' },
  { key: 'address_number'; name: 'Дом' },
  { key: 'address_building'; name: 'Корпус' },
  { key: 'address_kv'; name: 'Квартира' },
  { key: 'District'; name: 'Район' },
  { key: 'CustomerID'; name: 'ID_Абонента' },
  { key: 'Comment'; name: 'Комментарий' },
  { key: 'TicketID'; name: 'ИДЗаявки' },
  { key: 'loading_count'; name: 'КоличествоСчетчиковЗагрузка' },
  { key: 'planned_cost'; name: 'Плановаястоимость' }
];



// interface ccFields = keyof[]